CFO_System/CFO_System/blueprint/auth.py
from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import login_user, logout_user, login_required, current_user

from CFO_System.models import Administrator
from CFO_System.forms import LoginForm, RegisterForm
from CFO_System.utils import redirect_back
from CFO_System.models import User
from CFO_System.extensions import db

auth_bp = Blueprint("auth",__name__)


@auth_bp.route('/login',methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('customer.index')) # return to index if logged in

    form = LoginForm()
    if form.validate_on_submit():
        username = form.email.data
        password = form.password.data

        if username == 'admin':
            admin = Administrator.query.filter_by(administrator_name=username).first()
            if username == admin.administrator_name and admin.validate_password(password):
                login_user(admin)
                flash('Welcome back, admin.', 'info')
                # TODO: admin should redirect to another page
                return redirect_back()
            flash('Invalid username or password.', 'warning')
        else:
            user = User.query.filter_by(email=username).first()
            if user is not None and user.validate_password(form.password.data):
                login_user(user)
                flash('Login success.', 'info')
                return redirect_back()
            flash('Invalid email or password.', 'warning')
    return render_template('auth/login.html', form=form)

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('customer.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data.lower()
        password = form.password.data
        user = User(email=email, user_name=username)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        flash("Register success!")
        return redirect(url_for('.login'))
    return render_template('auth/register.html', form=form)

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout success.', 'info')
    return redirect(url_for('customer.index'))

CFO_System/CFO_System/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}校园订餐系统{% endblock %}</title>
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
</head>
<body>
<main class="container">
    <header>
        <h1 class="text-center display-4">
            <a href="{{ url_for('shop.index') }}" class="text-success"><strong>Campus Food Ordering System</strong></a>
            <p/><p/>
            <small class="text-muted sub-title">校园订餐系统</small>
        </h1>
    </header>
    {% for message in get_flashed_messages() %}
        <div class="alert alert-info">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
    {% endfor %}
    {% block navigator %}{% endblock %}
    {% block content %}{% endblock %}
    <footer class="text-center">
        {% block footer %}
            <small> &copy; 2020 <a href="https://github.com/CSC4001/Campus-Food-Ordering-System" title="CSC4001 Project">Campus Food Ordering System</a> /
            </small>
            <p><a id="bottom" href="#" title="Go Top">&uarr;</a></p>
            <p class="float-right">
                <small>
                    {% if current_user.is_authenticated %}
                        <p>Hello, {{ current_user.user_name }}!</p>
                        <a href="{{ url_for('auth.logout', next=request.full_path) }}">Logout</a>
                    {% else %}
                        <a  href="{{ url_for('auth.login', next=request.full_path) }}">Login</a>&nbsp;&nbsp;
                        <a  href="{{ url_for('auth.register') }}">Register</a>
                    {% endif %}
                </small>
            </p>
        {% endblock %}
    </footer>
</main>

<script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.2.1.slim.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
{{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
</body>
</html>